[package]
name = "ch09"
version = "0.1.0"
edition = "2024"

[features]
logging_decorator = []

[dependencies]
tokio = { version = "1.33", features = ["full"] }
uuid = { version = "1.5.0", features = ["v4"] } 